import { readFileSync } from 'node:fs';

import { describe, expect, it } from 'vitest';

import contract from '../../../openapi/backend-v1.json';

/**
 * El contrato OpenAPI es la única fuente de verdad. Estas pruebas fijan lo que el panel da por
 * cierto: si el backend cambia el contrato, fallan aquí en lugar de fallar en producción.
 */

const TYPES_PATH = 'src/lib/api/generated/schema.d.ts';

describe('copia versionada del contrato', () => {
  it('es un documento OpenAPI con las rutas de sesión administrativa', () => {
    expect(contract.openapi).toMatch(/^3\./);
    expect(contract.paths).toHaveProperty(['/v1/admin/auth/session']);
    expect(contract.paths['/v1/admin/auth/session']).toHaveProperty('post');
    expect(contract.paths['/v1/admin/auth/session']).toHaveProperty('get');
  });

  it('no publica ningún DELETE de la sesión: el BFF no puede inventarlo', () => {
    expect(contract.paths['/v1/admin/auth/session']).not.toHaveProperty('delete');
  });

  it('declara la sesión administrativa como apiKey en su propio encabezado', () => {
    expect(contract.components.securitySchemes.adminSession).toEqual({
      in: 'header',
      name: 'x-modulartess-admin-session',
      type: 'apiKey',
    });
  });

  it('devuelve el material de sesión solo en el encabezado de respuesta, nunca en el cuerpo', () => {
    const created = contract.paths['/v1/admin/auth/session'].post.responses['201'];

    expect(created.headers).toHaveProperty('x-modulartess-admin-session');
    expect(Object.keys(contract.components.schemas.AdminSessionCreatedDto.properties)).toEqual([
      'expiresAt',
      'principal',
    ]);
  });

  it('sigue publicando únicamente el rol super_admin', () => {
    // `master_admin` y `moderator` están decididos en la ADR 0007 del backend, pero todavía no
    // están implementados ni aparecen en el contrato.
    expect(contract.components.schemas.AdminPrincipalDto.properties.role.enum).toEqual([
      'super_admin',
    ]);

    const serialized = JSON.stringify(contract);

    expect(serialized).not.toContain('master_admin');
    expect(serialized).not.toContain('moderator');
  });

  it('fija los límites del idToken que replica la validación del BFF', () => {
    const { idToken } = contract.components.schemas.AdminSessionRequestDto.properties;

    expect(idToken.minLength).toBe(32);
    expect(idToken.maxLength).toBe(4096);
    expect(contract.components.schemas.AdminSessionRequestDto.required).toEqual(['idToken']);
  });
});

describe('tipos generados', () => {
  it('existen y provienen del generador, no de una edición a mano', () => {
    const generated = readFileSync(TYPES_PATH, 'utf8');

    expect(generated).toContain('auto-generated by openapi-typescript');
    expect(generated).toContain('/v1/admin/auth/session');
  });

  it('están sincronizados con la copia del contrato (lo verifica pnpm api:check)', () => {
    const generated = readFileSync(TYPES_PATH, 'utf8');

    // Toda ruta del contrato debe aparecer en los tipos generados.
    for (const path of Object.keys(contract.paths)) {
      expect(generated).toContain(`"${path}"`);
    }
  });
});
